feat: Check if nix link has existed

diff --git a/bin/common/pre-init-nix b/bin/common/pre-init-nix
--- a/bin/common/pre-init-nix
+++ b/bin/common/pre-init-nix
@@ -42,15 +42,21 @@ else
   ${nix_bin} --update
 fi
 
-# Link nix to /usr/local/bin
-if [ -f $HOME/.nix-profile/bin/nix ]; then
-  # linux
-  path_to_nix_bin=$HOME/.nix-profile/bin/nix
-else if [ -f /run/current-system/sw/bin/nix ]; then
-  # macos
-  path_to_nix_bin=/run/current-system/sw/bin/nix
+path_to_nix_link=/usr/local/bin/nix
+if [ -f ${path_to_nix_link} ]; then
+  echo "Info: nix has already linked! Skip."
 else
-  echo "Error: nix binary not found!"
-  exit 1
+  # Link nix to /usr/local/bin
+  if [ -f $HOME/.nix-profile/bin/nix ]; then
+    # linux
+    path_to_nix_bin=$HOME/.nix-profile/bin/nix
+  elif [ -f /run/current-system/sw/bin/nix ]; then
+    # macos
+    path_to_nix_bin=/run/current-system/sw/bin/nix
+  else
+    echo "Error: nix binary not found!"
+    exit 1
+  fi
+
+  sudo ln -sf ${path_to_nix_bin} ${path_to_nix_link}
 fi
-ln -sf ${path_to_nix_bin} /usr/local/bin/nix
